--  DDL for View TIES_GOOGLE_FEED_INFO_VW
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "TIES"."TIES_GOOGLE_FEED_INFO_VW" ("FEED_PUBLISHER_NAME", "FEED_PUBLISHER_URL", "FEED_LANG", "FEED_START_DATE", "FEED_END_DATE", "FEED_VERSION") AS 
  SELECT 'RTD' AS FEED_PUBLISHER_NAME,
          'http://rtd-denver.com' AS FEED_PUBLISHER_URL,
          'en' AS FEED_LANG,
          TO_CHAR (effective_timestamp, 'YYYYMMDD') FEED_START_DATE,
          TO_CHAR (termination_timestamp, 'YYYYMMDD') FEED_END_DATE,
             TRB.RUNBOARD_DESCRIPTION
          || '-'
          || TO_CHAR (TRB.RUNBOARD_ID)
          || '-'
          || TRB.RUNBOARD_REVISION
          || '-'
          || TO_CHAR (TRB.RUNBOARD_VERSION)
          || '-'
          || TO_CHAR (SYSDATE, 'YYYYMMDD-HH24MISS')
             AS FEED_VERSION
     FROM TIES_GOOGLE_RUNBOARD TGR
          JOIN TIES_RUNBOARDS TRB ON TGR.RUNBOARD_ID = TRB.RUNBOARD_ID
;
  GRANT SELECT ON "TIES"."TIES_GOOGLE_FEED_INFO_VW" TO "TIES_DS";
  GRANT SELECT ON "TIES"."TIES_GOOGLE_FEED_INFO_VW" TO "TIES_REPORT";
  GRANT SELECT ON "TIES"."TIES_GOOGLE_FEED_INFO_VW" TO "TIES_READ";
  GRANT SELECT ON "TIES"."TIES_GOOGLE_FEED_INFO_VW" TO "TIES_WEB";
  GRANT SELECT ON "TIES"."TIES_GOOGLE_FEED_INFO_VW" TO "TIES_READ_ROLE";
