services:
  # Apache Kafka with KRaft (no ZooKeeper) - ARM64 compatible
  kafka:
    image: bitnami/kafka:3.8.0  # Bitnami Kafka with native ARM64 support
    hostname: kafka
    container_name: rtd-kafka
    restart: unless-stopped
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      # KRaft configuration (Bitnami format)
      KAFKA_CFG_NODE_ID: 1
      KAFKA_CFG_PROCESS_ROLES: controller,broker
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_CFG_LISTENERS: PLAINTEXT://0.0.0.0:29092,CONTROLLER://0.0.0.0:9093,PLAINTEXT_HOST://0.0.0.0:9092
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      
      # Performance and storage settings (Bitnami format)
      KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CFG_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_CFG_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_CFG_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: 'true'
      
      # Log settings optimized for RTD data (Bitnami format)
      KAFKA_CFG_LOG_RETENTION_HOURS: 24
      KAFKA_CFG_LOG_RETENTION_BYTES: 1073741824  # 1GB
      KAFKA_CFG_LOG_SEGMENT_BYTES: 104857600     # 100MB
      KAFKA_CFG_LOG_CLEANUP_POLICY: delete
      
      # JVM settings for development
      KAFKA_HEAP_OPTS: "-Xmx1G -Xms1G"
      
    volumes:
      - kafka-data:/var/lib/kafka/data
      - /var/run/docker.sock:/var/run/docker.sock
    healthcheck:
      test: ["CMD-SHELL", "kafka-topics --bootstrap-server localhost:9092 --list"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    networks:
      - rtd-network

  # Kafka UI for easy management (optional)
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: rtd-kafka-ui
    restart: unless-stopped
    platform: linux/amd64  # Force x86_64 platform for compatibility
    ports:
      - "8090:8080"  # Changed from 8080 to 8090 to avoid conflict with RTD API
    environment:
      KAFKA_CLUSTERS_0_NAME: rtd-kafka-cluster
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
      KAFKA_CLUSTERS_0_PROPERTIES_SECURITY_PROTOCOL: PLAINTEXT
    depends_on:
      - kafka
    networks:
      - rtd-network

volumes:
  kafka-data:
    driver: local

networks:
  rtd-network:
    driver: bridge
    name: rtd-gtfs-network